"""The #115 proposal turn: ask the pinned worker for ONE harness
change in the standard pre-registration format.

Context given, per the registered protocol: the iteration history
(EVALS.md), the certified run's per-item outcomes, and the current
prompt prefix. Constraints stated to the model: exactly one change,
harness surfaces only (the graders, judge, validators, and mutation
gate are not its to touch), targeting the two named residual
buckets. The reply is committed verbatim before being applied.

Usage:
    uv run python scripts/propose_iteration.py \
        evals/runs/20260803T221121Z.jsonl \
        evals/proposals/115-proposal.md
"""

import json
import sys
from collections import defaultdict
from pathlib import Path

MODEL = "claude-opus-4-8"


def per_item_summary(run_path: str) -> str:
    rows = [json.loads(ln) for ln in Path(run_path).read_text().splitlines() if ln.strip()]
    by = defaultdict(list)
    for r in rows:
        by[r["scenario_id"]].append(r)
    lines = []
    for sid in sorted(by):
        trials = sorted(by[sid], key=lambda r: r["trial"])
        pattern = []
        fails: set[str] = set()
        calls = []
        for r in trials:
            d = r["dims"]
            if r["scenario_type"] == "control":
                ok = bool(d.get("honesty", {}).get("passed"))
            else:
                ok = bool(d.get("found_top3", {}).get("passed")) and bool(
                    d.get("evidence", {}).get("passed")
                )
            pattern.append("P" if ok else "F")
            fails |= {k for k, v in d.items() if not v["passed"]}
            calls.append(r["tool_calls"])
        lines.append(
            f"{sid}: trials={''.join(pattern)} tool_calls={calls}"
            + (f" failing_dims={sorted(fails)}" if fails else "")
        )
    return "\n".join(lines)


def main(run_path: str, out_path: str) -> None:
    from anthropic import Anthropic

    from resgraph.analyst.prompts import prefix_text

    evals_text = Path("EVALS.md").read_text()
    prompt = f"""You are the eval-design worker for resgraph's analyst harness.
Eight human-registered iterations produced the current certified
configuration. This turn is a registered experiment (#115): you
propose the ninth iteration. One proposal, then the gate decides.

Hard constraints:
- Propose exactly ONE change, in the pre-registration format the
  iteration log uses: Signal triage / Change (one) / Predicted /
  Invalidating result.
- Harness surfaces only: the prompt prefix (identity, discipline,
  tool guidance, output contract, worked examples) or harness
  configuration. The graders, judge, validators, and mutation gate
  are instruments — not yours to touch.
- Target the named residual buckets: EARLY CONCLUSION (transitive
  items missed as honest hedges with only 5-8 of 15 tool calls
  spent — budget never binds, the search stops early) and DECOY
  SEDUCTION (committed wrong answers on a planted confounder whose
  mechanism and event are real).
- The change must be concrete enough to apply verbatim: quote the
  exact text to add or replace, and where.
- Predicted effect must be numeric and falsifiable against a
  30-scenario trials=1 run; state the invalidating result the same
  way. Respect the honesty ordering: a prediction that trades
  controls for recall is a losing trade.

The iteration log (history, decisions, residual analysis):

<evals_log>
{evals_text}</evals_log>

The certified k=3 run, per item (P/F per trial, tool calls spent):

<per_item>
{per_item_summary(run_path)}</per_item>

The current prompt prefix, verbatim (your change edits this):

<prefix>
{prefix_text()}</prefix>

Reply with the proposal only, in markdown, ready to commit."""

    client = Anthropic()
    resp = client.messages.create(
        model=MODEL,
        max_tokens=16_000,
        thinking={"type": "adaptive"},
        messages=[{"role": "user", "content": prompt}],
    )
    text = "".join(b.text for b in resp.content if getattr(b, "type", None) == "text")
    usage = resp.usage
    header = (
        "# #115 proposal — generated by the pinned worker, committed verbatim\n\n"
        f"Model: {MODEL} | input tokens: {usage.input_tokens} | "
        f"output tokens: {usage.output_tokens}\n\n---\n\n"
    )
    Path(out_path).write_text(header + text.strip() + "\n")
    print(f"proposal -> {out_path} ({usage.output_tokens} output tokens)")


if __name__ == "__main__":
    main(*sys.argv[1:3])
